[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "velodatamap"
authors = [{name = "Idrissa Djepa Creutz", email = "sig@velo-territoires.org"}]
dynamic = ["version", "description"]
